#!/usr/bin/env python3

import os
import math
from config import *

# --- Configuration ---
BASE_SP_DIR = CALC_DIRS["base"]
DOPED_DIR = DOPED_MOLS_DIR

def distance(p1, p2):
    return math.sqrt(sum((a - b)**2 for a, b in zip(p1, p2)))

def read_xyz(filepath):
    """Reads XYZ, returns list of (atom_type, [x, y, z])."""
    atoms = []
    with open(filepath, 'r') as f:
        lines = f.readlines()
        if len(lines) < 3: return atoms
        for line in lines[2:]:
            parts = line.split()
            if len(parts) >= 4:
                atoms.append((parts[0], [float(parts[1]), float(parts[2]), float(parts[3])]))
    return atoms

def write_xyz(filepath, atoms):
    """Writes XYZ formatting exactly like Avogadro, stripping ORCA tags."""
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    with open(filepath, 'w') as f:
        f.write(f"{len(atoms)}\n")
        f.write("XYZ file generated by Avogadro.\n")
        for atom, coords in atoms:
            f.write(f"{atom:<5} {coords[0]:>14.10f} {coords[1]:>14.10f} {coords[2]:>14.10f}\n")

def get_center_of_geometry(atoms):
    x = sum(c[0] for _, c in atoms) / len(atoms)
    y = sum(c[1] for _, c in atoms) / len(atoms)
    z = sum(c[2] for _, c in atoms) / len(atoms)
    return [x, y, z]

def generate_for_molecule(mol_name):
    opt_xyz_path = os.path.join(BASE_SP_DIR, mol_name, "opt", f"{mol_name}_opt.xyz")
    if not os.path.exists(opt_xyz_path):
        print(f"[!] Skipping {mol_name}: No optimized geometry found at {opt_xyz_path}")
        return

    # Apply strict rules
    rules = SYMMETRY_RULES.get(mol_name, {"X_sym": True, "Y_sym": True})
    has_x = rules["X_sym"]
    has_y = rules["Y_sym"]

    atoms = read_xyz(opt_xyz_path)
    cog = get_center_of_geometry(atoms)

    # 1. Identify Edge Carbons and map to their attached Hydrogens
    edge_carbons = {} # dict mapping C_index -> H_index
    for i, (atom_i, coords_i) in enumerate(atoms):
        if atom_i == 'C':
            for j, (atom_j, coords_j) in enumerate(atoms):
                if atom_j == 'H' and distance(coords_i, coords_j) < CH_BOND_MAX:
                    edge_carbons[i] = j
                    break # Assuming 1 H per edge C

    # 2. Shift to origin for mathematical symmetry checking
    centered = [[c[0]-cog[0], c[1]-cog[1], c[2]-cog[2]] for _, c in atoms]

    # 3. Group Equivalent Edge Carbons
    unique_groups = []
    visited_carbons = set()

    for c_idx in edge_carbons.keys():
        if c_idx in visited_carbons: continue
        
        cx, cy, cz = centered[c_idx]
        
        # Determine mathematical reflection targets
        targets = [(cx, cy)]
        if has_x: targets.append((cx, -cy))
        if has_y: targets.append((-cx, cy))
        if has_x and has_y: targets.append((-cx, -cy))

        current_group = set()
        for tx, ty in targets:
            best_dist = SYM_TOLERANCE
            best_idx = -1
            for search_idx in edge_carbons.keys():
                dist = distance([tx, ty, 0], [centered[search_idx][0], centered[search_idx][1], 0])
                if dist < best_dist:
                    best_dist = dist
                    best_idx = search_idx
            
            if best_idx != -1:
                current_group.add(best_idx)
                visited_carbons.add(best_idx)
        
        if current_group:
            unique_groups.append(list(current_group))

    # 4. Sort Groups Clockwise (Strictly 12 o'clock -> 3 -> 6 -> 9)
    def group_angle(group):
        min_angle = 2 * math.pi
        for idx in group:
            x, y, _ = centered[idx]
            # atan2(x,y) locks 0 at the top (positive Y) and sweeps clockwise
            angle = math.atan2(x, y)
            if angle < 0:
                angle += 2 * math.pi # Wrap negative angles into a clean 0 to 2pi sweep
            if angle < min_angle:
                min_angle = angle
        return min_angle
    
    # Sort groups by whichever atom in that group is closest to 12 o'clock clockwise
    unique_groups.sort(key=group_angle)

    print(f"\n--- {mol_name} ---")
    print(f"Applied Rules: X-Symmetry = {has_x}, Y-Symmetry = {has_y}")
    print(f"Discovered {len(unique_groups)} unique topological substitution sites.")

    # 5. Generate N and B doped molecules
    for pos_num, group in enumerate(unique_groups, start=1):
        h_to_delete = {edge_carbons[c_idx] for c_idx in group}

        print(f"  -> Site P{pos_num}: Swapping {len(group)} Carbon(s)")

        for dopant in ['N', 'B']:
            new_atoms = []
            for idx, (atom_type, coords) in enumerate(atoms):
                if idx in h_to_delete:
                    continue # Delete the Hydrogen
                if idx in group:
                    new_atoms.append((dopant, coords)) # Swap C for Dopant
                else:
                    new_atoms.append((atom_type, coords)) # Keep standard atom
            
            out_name = f"{mol_name}_P{pos_num}{dopant}.xyz"
            out_path = os.path.join(DOPED_DIR, mol_name, out_name)
            write_xyz(out_path, new_atoms)

def main():
    if not os.path.exists(BASE_SP_DIR):
        print(f"Error: Could not find {BASE_SP_DIR}. Have you run base_scheduler.py yet?")
        return
        
    mols = [d for d in os.listdir(BASE_SP_DIR) if os.path.isdir(os.path.join(BASE_SP_DIR, d))]
    
    print("==================================================")
    print("             Doped Molecule Generator             ")
    print("==================================================")
    
    for mol in sorted(mols):
        generate_for_molecule(mol)
        
    print("\nGeneration Complete. Check the doped_molecules/ directory.")

if __name__ == "__main__":
    main()