#!/usr/bin/env python3

import os
import math
from config import *

# --- Configuration ---
BASE_SP_DIR = CALC_DIRS["base"]
DOUBLE_DOPED_DIR = DOUBLE_DOPED_MOLS_DIR

def distance(p1, p2):
    return math.sqrt(sum((a - b)**2 for a, b in zip(p1, p2)))

def read_xyz(filepath):
    """Reads XYZ, returns list of (atom_type, [x, y, z])."""
    atoms = []
    with open(filepath, 'r') as f:
        lines = f.readlines()
        if len(lines) < 3: return atoms
        for line in lines[2:]:
            parts = line.split()
            if len(parts) >= 4:
                atoms.append((parts[0], [float(parts[1]), float(parts[2]), float(parts[3])]))
    return atoms

def write_xyz(filepath, atoms):
    """Writes XYZ formatting exactly like Avogadro."""
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    with open(filepath, 'w') as f:
        f.write(f"{len(atoms)}\n")
        f.write("XYZ file generated by Avogadro.\n")
        for atom, coords in atoms:
            f.write(f"{atom:<5} {coords[0]:>14.10f} {coords[1]:>14.10f} {coords[2]:>14.10f}\n")

def get_center_of_geometry(atoms):
    x = sum(c[0] for _, c in atoms) / len(atoms)
    y = sum(c[1] for _, c in atoms) / len(atoms)
    z = sum(c[2] for _, c in atoms) / len(atoms)
    return [x, y, z]

def discover_substitution_sites(mol_name, atoms):
    rules = SYMMETRY_RULES.get(mol_name, {"X_sym": False, "Y_sym": False})
    has_x = rules["X_sym"]
    has_y = rules["Y_sym"]

    cog = get_center_of_geometry(atoms)

    # 1. Identify Edge Carbons and map to their attached Hydrogens
    edge_carbons = {} 
    for i, (atom_i, coords_i) in enumerate(atoms):
        if atom_i == 'C':
            for j, (atom_j, coords_j) in enumerate(atoms):
                if atom_j == 'H' and distance(coords_i, coords_j) < CH_BOND_MAX:
                    edge_carbons[i] = j
                    break 

    # 2. Shift to origin for mathematical symmetry checking
    centered = [[c[0]-cog[0], c[1]-cog[1], c[2]-cog[2]] for _, c in atoms]

    # 3. Group Equivalent Edge Carbons
    unique_groups = []
    visited_carbons = set()

    for c_idx in edge_carbons.keys():
        if c_idx in visited_carbons: continue
        
        cx, cy, cz = centered[c_idx]
        
        targets = [(cx, cy)]
        if has_x: targets.append((cx, -cy))
        if has_y: targets.append((-cx, cy))
        if has_x and has_y: targets.append((-cx, -cy))

        current_group = set()
        for tx, ty in targets:
            best_dist = SYM_TOLERANCE
            best_idx = -1
            for search_idx in edge_carbons.keys():
                dist = distance([tx, ty, 0], [centered[search_idx][0], centered[search_idx][1], 0])
                if dist < best_dist:
                    best_dist = dist
                    best_idx = search_idx
            
            if best_idx != -1:
                current_group.add(best_idx)
                visited_carbons.add(best_idx)
        
        if current_group:
            unique_groups.append(list(current_group))

    # 4. Sort Groups Clockwise
    def group_angle(group):
        min_angle = 2 * math.pi
        for idx in group:
            x, y, _ = centered[idx]
            angle = math.atan2(x, y)
            if angle < 0: angle += 2 * math.pi 
            if angle < min_angle: min_angle = angle
        return min_angle
    
    unique_groups.sort(key=group_angle)
    return unique_groups, edge_carbons

def generate_double_doped(mol_name):
    opt_xyz_path = os.path.join(BASE_SP_DIR, mol_name, "opt", f"{mol_name}_opt.xyz")
    if not os.path.exists(opt_xyz_path):
        print(f"[!] Error: No optimized geometry found at {opt_xyz_path}")
        return

    atoms = read_xyz(opt_xyz_path)
    unique_groups, edge_carbons = discover_substitution_sites(mol_name, atoms)

    print(f"\n--- {mol_name} ---")
    print(f"Discovered {len(unique_groups)} unique topological substitution sites.")
    for i, g in enumerate(unique_groups, 1):
        print(f"  P{i}: {len(g)} atoms dynamically mapped.")

    combinations = []

    if mol_name == "CirCor":
        combinations = [
            (2, 5, 'N', 'N'), (2, 5, 'B', 'B'), (2, 5, 'N', 'B'), (2, 5, 'B', 'N'),
            (2, 3, 'N', 'N'), (2, 3, 'B', 'B'), (2, 3, 'N', 'B'), (2, 3, 'B', 'N'),
            (2, 4, 'N', 'N'), (2, 4, 'B', 'B'), (2, 4, 'N', 'B'), (2, 4, 'B', 'N'),
            (3, 5, 'N', 'N'), (3, 5, 'B', 'B'), (3, 5, 'N', 'B'), (3, 5, 'B', 'N'),
            (4, 5, 'N', 'N'), (4, 5, 'B', 'B'), (4, 5, 'N', 'B'), (4, 5, 'B', 'N'),
            (3, 4, 'N', 'B'), (3, 4, 'B', 'N')
        ]
    elif mol_name == "AsymPAH2":
        # Generate combinations dynamically
        # Exclude P1 (which is index 1, so we start the loop at 2)
        for i in range(2, len(unique_groups) + 1):
            for j in range(i + 1, len(unique_groups) + 1):
                
                group_i = unique_groups[i-1]
                group_j = unique_groups[j-1]
                
                # Robust adjacency check: test all atoms in site i against all in site j
                is_adjacent = False
                for idx_i in group_i:
                    for idx_j in group_j:
                        if distance(atoms[idx_i][1], atoms[idx_j][1]) < CC_ADJACENT_MAX:
                            is_adjacent = True
                            break
                    if is_adjacent: break
                
                if is_adjacent:
                    # Adjacent: Allow B-N and N-B only
                    combinations.extend([
                        (i, j, 'N', 'B'),
                        (i, j, 'B', 'N')
                    ])
                else:
                    # Not adjacent: Allow all 4
                    combinations.extend([
                        (i, j, 'N', 'N'),
                        (i, j, 'B', 'B'),
                        (i, j, 'N', 'B'),
                        (i, j, 'B', 'N')
                    ])

    count = 0
    for p1, p2, d1, d2 in combinations:
        group1 = unique_groups[p1 - 1]
        group2 = unique_groups[p2 - 1]
        
        h_to_delete = {edge_carbons[c] for c in group1} | {edge_carbons[c] for c in group2}

        new_atoms = []
        for idx, (atom_type, coords) in enumerate(atoms):
            if idx in h_to_delete:
                continue # Strip Hydrogen
            if idx in group1:
                new_atoms.append((d1, coords)) # Insert Dopant 1
            elif idx in group2:
                new_atoms.append((d2, coords)) # Insert Dopant 2
            else:
                new_atoms.append((atom_type, coords)) # Keep standard C/H
        
        out_name = f"{mol_name}_P{p1}{d1}_P{p2}{d2}.xyz"
        out_path = os.path.join(DOUBLE_DOPED_DIR, mol_name, out_name)
        write_xyz(out_path, new_atoms)
        count += 1

    print(f"Successfully generated {count} dual-doped .xyz files in {DOUBLE_DOPED_DIR}/{mol_name}.")


def main():
    print("==================================================")
    print("      Double Doped Generator (Batch Mode)         ")
    print("==================================================")
    generate_double_doped("CirCor")
    generate_double_doped("AsymPAH2")

if __name__ == "__main__":
    main()